'use strict';
const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const esc = s => String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let session, project, selected, file, word, page=1, pageInfo, filter='all', mode='edit', timer, dirty=false, inFlight=false, saving=Promise.resolve(), routeVersion=0, cropMode=false, cropBox=null, pointerStart, toastTimer;
const section = () => project?.sections.find(s=>s.id===selected);
const base = () => `/api/projects/${project.id}`;
async function api(path,body,raw=false,attempt=0){
  const response=await fetch(path,body===undefined?{}:{method:'POST',headers:{'X-Dissector-Token':session.token,...(raw?{}:{'Content-Type':'application/json'})},body:raw?body:JSON.stringify(body)});
  const data=await response.json();
  if(response.status===403&&attempt===0&&body!==undefined&&String(data.error).startsWith('Session expired')){session=await api('/api/session');return api(path,body,raw,1);}
  if(!response.ok) throw Error(data.error||'The operation could not finish.');
  return data;
}
function toast(message, error=false){$('#toast').textContent=message;$('#toast').hidden=false;$('#toast').style.background=error?'#7a303b':'#32243d';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,error?9000:4500);}
function busy(button, state){button.disabled=state;button.setAttribute('aria-busy',String(state));}
function modal(content){$('#modal-content').innerHTML=content;$('#modal').showModal();$$('[data-close]').forEach(b=>b.onclick=()=>$('#modal').close());}
function markDirty(){dirty=true;$('#save-state').textContent='Unsaved changes';clearTimeout(timer);timer=setTimeout(()=>save().catch(()=>{}),850);}
async function save(){
  clearTimeout(timer);
  // Serialize saves and take the snapshot only after the preceding save finishes.
  saving=saving.catch(()=>{}).then(async()=>{
    if(!project||!dirty)return;
    const p=project, snapshot=JSON.parse(JSON.stringify(p));dirty=false;inFlight=true;$('#save-state').textContent='Saving…';
    try{const result=await api(`/api/projects/${p.id}/save`,snapshot);p.revision=result.revision;p.updated=result.updated;$('#save-state').textContent=dirty?'Unsaved changes':'Saved locally';}
    catch(error){if(project===p)dirty=true;$('#save-state').textContent='Save failed';toast(error.message,true);throw error;}finally{inFlight=false;}
  });
  return saving;
}
function edited(){const s=section();if(!s)return;s.status='draft';markDirty();updateReview();renderOutline();}
function capture(){const s=section();if(!s)return;s.title=$('#section-title').value;s.markdown=$('#markdown').value;s.group=$('#section-group').value;s.kind=$('#section-kind').value;edited();resizeTitle();}
function resizeTitle(){$('#section-title').style.height='auto';$('#section-title').style.height=$('#section-title').scrollHeight+'px';}
function setFile(next){if(!next)return;if(!next.name.toLowerCase().endsWith('.pdf'))return toast('Choose a PDF file.',true);if(next.size>200*1024*1024)return toast('Choose a PDF smaller than 200 MB.',true);file=next;$('#file-label').textContent=next.name;$('#file-description').textContent=`${(next.size/1024/1024).toFixed(1)} MB · ready to convert`;$('#convert-button').disabled=false;}
$('#pdf-file').onchange=e=>setFile(e.target.files[0]);
$('#word-file').onchange=e=>{word=e.target.files[0];if(!word)return;if(!word.name.toLowerCase().endsWith('.docx')||word.size>200*1024*1024){word=null;return toast('Choose a .docx file smaller than 200 MB.',true);}$('#word-label').firstChild.textContent=word.name;$('#remove-word').hidden=false;};
$('#remove-word').onclick=()=>{word=null;$('#word-file').value='';$('#word-label').firstChild.textContent='Add Word file';$('#remove-word').hidden=true;};
const drop=$('#drop-zone');['dragenter','dragover'].forEach(name=>drop.addEventListener(name,e=>{e.preventDefault();drop.classList.add('dragover');}));['dragleave','drop'].forEach(name=>drop.addEventListener(name,e=>{e.preventDefault();drop.classList.remove('dragover');}));drop.addEventListener('drop',e=>setFile(e.dataTransfer.files[0]));
$('#convert-button').onclick=async()=>{if(!file)return;const button=$('#convert-button');busy(button,true);$('#upload-progress').hidden=false;try{const job=await api('/api/projects?name='+encodeURIComponent(file.name),file,true);if(word)await api(`/api/projects/${job.id}/word`,word,true);await api(`/api/projects/${job.id}/convert`,{});location.hash=`project/${job.id}`;}catch(error){toast(error.message,true);}finally{busy(button,false);$('#upload-progress').hidden=true;}};
$('#back-home').onclick=()=>location.hash='';
async function home(){const jobs=await api('/api/projects');$('#conversion-count').textContent=`${jobs.length} ${jobs.length===1?'conversion':'conversions'}`;$('#recent-list').innerHTML=jobs.length?jobs.map(j=>`<a class="conversion-card" href="#project/${j.id}"><span class="eyebrow">${j.status==='ready'?'READY FOR REVIEW':esc(j.phase)}</span><h3>${esc(j.title)}</h3><small>${j.pages?`${j.pages} pages · ${j.sections} sections · ${j.reviewed||0} reviewed`:'Continue conversion'} <span aria-hidden="true">↗</span></small></a>`).join(''):'<div class="empty-state">Your first conversion will appear here. Start with a PDF above.</div>';}
async function route(){
  const version=++routeVersion;
  try{await save();}catch(error){return;}
  const match=location.hash.match(/^#project\/([a-f0-9]{12})(?:\/(s-[a-zA-Z0-9_-]+))?$/);
  ['home','processing','workspace'].forEach(id=>$('#'+id).hidden=true);$('#export-button').hidden=true;$('#project-name').textContent='';$('#save-state').textContent='';
  if(!match){project=null;selected=null;$('#home').hidden=false;document.title='Guide Dissector';await home();return;}
  const id=match[1];
  try{
    const job=await api(`/api/projects/${id}/job`);if(version!==routeVersion)return;
    if(job.status!=='ready'){
      project=null;$('#processing').hidden=false;$('#processing-file').textContent=job.filename;$('#processing-phase').textContent=job.phase;$('#processing-count').textContent=job.total?`${job.current} / ${job.total}`:'';
      $('#progress-fill').style.width=(job.total?100*job.current/job.total:2)+'%';$('#processing-error').hidden=!['error','uploaded'].includes(job.status);
      if(job.status==='error'||job.status==='uploaded'){
        $('#processing-error').innerHTML=`<p>${esc(job.error||'Your file is copied and ready to convert.')}</p><button class="primary" id="retry">${job.status==='error'?'Retry conversion':'Start conversion'}</button>`;
        $('#retry').onclick=async()=>{try{await api(`/api/projects/${id}/convert`,{});route();}catch(e){toast(e.message,true);}};
      } else setTimeout(()=>{if(version===routeVersion)route();},1300);
      return;
    }
    project=await api(`/api/projects/${id}`);if(version!==routeVersion)return;
    $('#workspace').hidden=false;$('#export-button').hidden=false;$('#project-name').textContent=project.title;$('#save-state').textContent='Saved locally';document.title=`${project.title} · Guide Dissector`;
    $('#total-pages').textContent='/ '+project.source.pages;$('#page-number').max=project.source.pages;filter='all';$('#outline-search').value='';$$('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===filter));
    selected=project.sections.some(s=>s.id===match[2])?match[2]:project.sections[0]?.id;renderOutline();if(selected)loadSection();
  }catch(error){toast(error.message,true);$('#home').hidden=false;await home();}
}
window.addEventListener('hashchange',route);
function renderOutline(){
  if(!project)return;const q=$('#outline-search').value.toLowerCase();let last='';
  const sections=project.sections.filter(s=>(filter!=='review'||s.status!=='reviewed')&&`${s.title} ${s.group} ${s.markdown}`.toLowerCase().includes(q));
  $('#outline').innerHTML=sections.map(s=>{let title='';if(s.group!==last){last=s.group;title=`<div class="outline-group">${esc(s.group||'Ungrouped')}</div>`;}return title+`<button class="outline-item ${selected===s.id?'active':''} ${s.status} ${s.included?'':'excluded'}" data-section="${s.id}" ${selected===s.id?'aria-current="page"':''}><span class="status-dot" aria-hidden="true"></span><span>${esc(s.title||'Untitled section')}</span></button>`;}).join('')||'<p class="muted" style="padding:12px;font-size:12px">No matching sections.</p>';
  $('#review-count').textContent=project.sections.filter(s=>s.status!=='reviewed').length;$('#section-count').textContent=`${project.sections.length} sections · ${project.sections.filter(s=>s.status==='reviewed').length} reviewed`;
  $$('[data-section]').forEach(b=>b.onclick=async()=>{try{await save();selected=b.dataset.section;history.replaceState(null,'',`#project/${project.id}/${selected}`);renderOutline();loadSection();}catch{}});
}
$('#outline-search').oninput=renderOutline;$$('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;$$('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderOutline();});
function loadSection(){const s=section();if(!s)return;cancelCrop();$('#section-title').value=s.title;$('#section-kind').value=s.kind;$('#section-group').value=s.group;$('#markdown').value=s.markdown;$('#source-pages').textContent='p. '+s.pages.join(', ');$('#excluded-badge').hidden=s.included;$('#issues').innerHTML=s.issues.map(i=>`<li>${esc(i)}</li>`).join('');$('#issue-count').textContent=s.issues.length;$('#review-notes').hidden=!s.issues.length;$('#review-notes').open=false;$('#editor-content').scrollTop=0;setMode(mode);updateReview();renderAssets();showPage(s.pages[0]||1);resizeTitle();}
function updateReview(){const s=section();$('#review-button').innerHTML=s.status==='reviewed'?'Reviewed ✓':'Mark reviewed <span>✓</span>';$('#review-button').classList.toggle('reviewed',s.status==='reviewed');$('#exclude-button').textContent=s.included?'Exclude section':'Restore section';$('#excluded-badge').hidden=s.included;const i=project.sections.indexOf(s);$('#move-up').disabled=i===0;$('#move-down').disabled=i===project.sections.length-1;$('#merge-button').disabled=i===project.sections.length-1;}
['section-title','section-group','markdown'].forEach(id=>$('#'+id).addEventListener('input',capture));$('#section-kind').onchange=capture;
function inline(text){return esc(text).replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g,'<a href="$2" target="_blank" rel="noopener noreferrer">$1 ↗</a>');}
function markdown(text){
  const lines=text.split('\n');let result='',paragraph=[],list=false,code=false,codeLines=[];
  const flush=()=>{if(paragraph.length){result+='<p>'+inline(paragraph.join(' '))+'</p>';paragraph=[];}if(list){result+='</ul>';list=false;}};
  for(let i=0;i<lines.length;i++){
    const l=lines[i],image=l.match(/^!\[([^\]]*)\]\(([^)]+)\)\s*$/),heading=l.match(/^(#{1,6})\s+(.*)/),bullet=l.match(/^\s*(?:[-*]|\d+[.)])\s+(.*)/);
    if(l.startsWith('```')){flush();if(code){result+='<pre><code>'+esc(codeLines.join('\n'))+'</code></pre>';codeLines=[];}code=!code;continue;}
    if(code){codeLines.push(l);continue;}
    if(image){flush();const a=project.assets.find(a=>'../'+a.path===image[2]);result+=a?`<img loading="lazy" src="${base()}/${a.path}" alt="${esc(image[1])}">`:`<p>Image reference needs review: ${esc(image[2])}</p>`;}
    else if(heading){flush();const n=Math.min(6,heading[1].length);result+=`<h${n}>${inline(heading[2])}</h${n}>`;}
    else if(l.trim().startsWith('|')&&lines[i+1]?.match(/^\s*\|?\s*:?-{3}/)){flush();let rows=[l];i+=2;while(i<lines.length&&lines[i].trim().startsWith('|'))rows.push(lines[i++]);i--;result+='<table>'+rows.map((row,j)=>'<tr>'+row.trim().replace(/^\||\|$/g,'').split(/(?<!\\)\|/).map(c=>`<${j?'td':'th'}>${inline(c.trim().replace(/\\\|/g,'|')).replace(/&lt;br&gt;/g,'<br>')}</${j?'td':'th'}>`).join('')+'</tr>').join('')+'</table>';}
    else if(bullet){if(paragraph.length)flush();if(!list){result+='<ul>';list=true;}result+='<li>'+inline(bullet[1])+'</li>';}
    else if(!l.trim()){flush();}else{paragraph.push(l);}
  }
  flush();if(code)result+='<pre>'+esc(codeLines.join('\n'))+'</pre>';return result;
}
function setMode(next){mode=next;$('#markdown').hidden=mode!=='edit';$('#markdown-preview').hidden=mode!=='preview';$('#edit-tab').classList.toggle('active',mode==='edit');$('#preview-tab').classList.toggle('active',mode==='preview');$('#split-button').disabled=mode!=='edit';if(mode==='preview')$('#markdown-preview').innerHTML=markdown(section().markdown);}
$('#edit-tab').onclick=()=>setMode('edit');$('#preview-tab').onclick=()=>setMode('preview');
$('#review-button').onclick=()=>{const s=section();s.status=s.status==='reviewed'?'draft':'reviewed';markDirty();updateReview();renderOutline();};
$('#exclude-button').onclick=()=>{const s=section();if(!s.included){s.included=true;s.exclusion_reason='';edited();updateReview();return;}modal(`<p class="eyebrow">CONTENT DECISION</p><h2>Exclude this section?</h2><p>The original remains in your local conversion. The exported manifest will record the exclusion and your reason.</p><label>Reason<textarea id="exclude-reason" rows="3" placeholder="For example: instructor scheduling notes"></textarea></label><div class="actions"><button class="secondary" data-close>Cancel</button><button class="primary" id="confirm-exclude">Exclude section</button></div>`);$('#confirm-exclude').onclick=()=>{const reason=$('#exclude-reason').value.trim();if(!reason)return toast('Add a reason for excluding this section.',true);s.included=false;s.exclusion_reason=reason;edited();updateReview();$('#modal').close();};};
function move(delta){const i=project.sections.findIndex(s=>s.id===selected),j=i+delta;if(j<0||j>=project.sections.length)return;[project.sections[i],project.sections[j]]=[project.sections[j],project.sections[i]];markDirty();renderOutline();updateReview();}
$('#move-up').onclick=()=>move(-1);$('#move-down').onclick=()=>move(1);
$('#split-button').onclick=()=>{const s=section(),cursor=$('#markdown').selectionStart;if(cursor<1||cursor>=s.markdown.length)return toast('Place the cursor inside the Markdown where a new section should begin.');const next=JSON.parse(JSON.stringify(s));next.id='s-'+crypto.randomUUID().replaceAll('-','');next.title=s.title+' — continued';next.markdown=s.markdown.slice(cursor).trim();s.markdown=s.markdown.slice(0,cursor).trim();s.status=next.status='draft';next.issues=[...new Set([...next.issues,'Section split manually; source references cover the original section. Review the new boundary.'])];project.sections.splice(project.sections.indexOf(s)+1,0,next);selected=next.id;markDirty();renderOutline();loadSection();toast('Section split. Give the new section a title.');};
$('#merge-button').onclick=()=>{const s=section(),i=project.sections.indexOf(s),next=project.sections[i+1];if(!next)return;modal(`<p class="eyebrow">COMBINE SECTIONS</p><h2>Merge with the next section</h2><p><strong>${esc(next.title)}</strong> will become part of this section. Its source references and images will be retained.</p><div class="actions"><button class="secondary" data-close>Cancel</button><button class="primary" id="confirm-merge">Merge sections</button></div>`);$('#confirm-merge').onclick=()=>{s.markdown+=`\n\n## ${next.title}\n\n${next.markdown}`;for(const k of ['source_ids','pages','asset_ids','issues'])s[k]=[...new Set([...s[k],...next[k]])];s.pages.sort((a,b)=>a-b);s.status='draft';project.sections.splice(i+1,1);markDirty();$('#modal').close();renderOutline();loadSection();};};
let sourceVersion=0;
async function showPage(number){if(!project)return;page=Math.max(1,Math.min(project.source.pages,Number(number)||1));pageInfo=null;const version=++sourceVersion;$('#page-number').value=page;$('#source-image').alt=`Original PDF, page ${page}`;$('#source-image').src=base()+'/page/'+page;$('#page-error').hidden=true;$('#previous-page').disabled=page===1;$('#next-page').disabled=page===project.source.pages;$('#source-size').textContent='';cancelCrop();try{const data=await api(base()+'/evidence/'+page);if(version!==sourceVersion)return;pageInfo=data;$('#source-size').textContent=`${Math.round(data.page.width)} × ${Math.round(data.page.height)} pt`;}catch(e){toast(e.message,true);}}
$('#source-zoom').onchange=e=>{$('#page-stage').style.width=e.target.value+'%';cancelCrop();};
$('#source-image').onerror=()=>{$('#page-error').textContent='This page could not be rendered. Try another page or check the terminal.';$('#page-error').hidden=false;};$('#previous-page').onclick=()=>showPage(page-1);$('#next-page').onclick=()=>showPage(page+1);$('#page-number').onchange=e=>showPage(e.target.value);
function renderAssets(){const s=section();const referenced=[...s.markdown.matchAll(/!\[[^\]]*\]\(\.\.\/(assets\/[^)]+)\)/g)].map(m=>m[1]);const assets=project.assets.filter(a=>referenced.includes(a.path));$('#asset-count').textContent=assets.length;$('#asset-list').innerHTML=assets.length?assets.map(a=>`<button class="asset-thumb" data-asset="${a.id}" aria-label="Review illustration on page ${a.page}"><img loading="lazy" src="${base()}/${a.path}" alt=""><span>Page ${a.page} ↗</span></button>`).join(''):'<span class="muted">Capture an illustration from the source page.</span>';$$('[data-asset]').forEach(b=>b.onclick=()=>{const a=project.assets.find(x=>x.id===b.dataset.asset);modal(`<p class="eyebrow">SOURCE ILLUSTRATION · PAGE ${a.page}</p><h2>Keep the context in view.</h2><img class="image-detail" src="${base()}/${a.path}" alt="${esc(a.caption)}"><p>To replace this image, capture a new crop on the source page and remove the old image line from Markdown.</p><div class="actions"><button class="secondary" data-close>Close</button><button class="primary" id="locate-asset">View source page</button></div>`);$('#locate-asset').onclick=()=>{$('#modal').close();showPage(a.page);};});}
$('#evidence-button').onclick=()=>{if(!pageInfo)return;modal(`<p class="eyebrow">EXTRACTION EVIDENCE · PAGE ${page}</p><h2>What the PDF contains.</h2><p>Raw lines are retained even when page furniture is omitted from the editable content.</p><pre>${esc(pageInfo.page.lines.map(l=>`${l.id}  ${l.text}\n  → ${pageInfo.ledger.find(x=>x.id===l.id)?.disposition||'retained'}`).join('\n\n'))}</pre><div class="actions"><button class="secondary" data-close>Close</button></div>`);};
function cancelCrop(){cropMode=false;cropBox=null;$('#crop-help').hidden=true;$('#crop-selection').hidden=true;$('#page-stage').classList.remove('cropping');$('#save-crop').disabled=true;}
$('#crop-button').onclick=()=>{if(!pageInfo||!$('#source-image').complete||!$('#source-image').naturalWidth)return toast('Wait for the source page to finish loading.');cropMode=true;cropBox=null;$('#crop-help').hidden=false;$('#page-stage').classList.add('cropping');$('#crop-selection').hidden=true;$('#save-crop').disabled=true;};$('#cancel-crop').onclick=cancelCrop;
$('#whole-page').onclick=()=>{cropBox=[0,0,1,1];const box=$('#crop-selection');box.hidden=false;Object.assign(box.style,{left:'0',top:'0',width:'100%',height:'100%'});$('#save-crop').disabled=false;};
function point(event){const r=$('#page-stage').getBoundingClientRect();return [Math.max(0,Math.min(1,(event.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(event.clientY-r.top)/r.height))];}
$('#page-stage').onpointerdown=e=>{if(!cropMode)return;e.preventDefault();pointerStart=point(e);$('#page-stage').setPointerCapture(e.pointerId);};
$('#page-stage').onpointermove=e=>{if(!cropMode||!pointerStart)return;const p=point(e);cropBox=[Math.min(p[0],pointerStart[0]),Math.min(p[1],pointerStart[1]),Math.max(p[0],pointerStart[0]),Math.max(p[1],pointerStart[1])];const box=$('#crop-selection');box.hidden=false;Object.assign(box.style,{left:cropBox[0]*100+'%',top:cropBox[1]*100+'%',width:(cropBox[2]-cropBox[0])*100+'%',height:(cropBox[3]-cropBox[1])*100+'%'});};
$('#page-stage').onpointerup=()=>{pointerStart=null;$('#save-crop').disabled=!cropBox||(cropBox[2]-cropBox[0])<.01||(cropBox[3]-cropBox[1])<.01;};
$('#save-crop').onclick=async()=>{if(!cropBox||!pageInfo)return;const button=$('#save-crop');busy(button,true);try{await save();const s=section(),w=pageInfo.page.width,h=pageInfo.page.height;const result=await api(base()+'/crop',{page,box:[cropBox[0]*w,cropBox[1]*h,cropBox[2]*w,cropBox[3]*h],revision:project.revision});project.assets.push(result.asset);project.revision=result.revision;const insertion=`\n\n![${result.asset.caption}](../${result.asset.path})\n\n`;const cursor=$('#markdown').selectionStart;s.markdown=s.markdown.slice(0,cursor)+insertion+s.markdown.slice(cursor);s.asset_ids.push(result.asset.id);s.source_ids.push(result.asset.id);s.pages=[...new Set([...s.pages,page])].sort((a,b)=>a-b);s.status='draft';markDirty();$('#markdown').value=s.markdown;setMode(mode);renderAssets();renderOutline();updateReview();cancelCrop();toast('Illustration added at the Markdown cursor.');}catch(e){toast(e.message,true);}finally{busy(button,false);}};
$('#document-settings').onclick=()=>{modal(`<p class="eyebrow">DOCUMENT DETAILS</p><h2>A little context goes a long way.</h2><label>Guide title<input id="doc-title" value="${esc(project.title)}"></label><label>Classification / handling label<input id="doc-classification" value="${esc(project.classification)}"></label><p>${project.source.pages} source pages · ${project.assets.length} captured illustrations · ${project.source.word_hints} Word heading hints</p><details><summary>Detected source markings</summary><pre>${esc(project.source_markings.join('\n')||'No markings detected. Check the original document.')}</pre></details><p>Changing this label does not change the source document’s handling requirements.</p><div class="actions"><button class="secondary" data-close>Cancel</button><button class="primary" id="save-details">Save details</button></div>`);$('#save-details').onclick=()=>{const title=$('#doc-title').value.trim(),classification=$('#doc-classification').value.trim();if(!title||!classification)return toast('Add a title and handling label.',true);project.title=title;project.classification=classification;markDirty();$('#project-name').textContent=title;document.title=`${title} · Guide Dissector`;$('#modal').close();};};
$('#export-button').onclick=()=>{const pending=project.sections.filter(s=>s.included&&s.status!=='reviewed').length;modal(`<p class="eyebrow">PORTABLE CONTENT PACKAGE</p><h2>Ready for its next chapter.</h2><p>Your ZIP contains editable Markdown, referenced images, a navigation manifest, and extraction evidence.</p><p><strong>${project.sections.filter(s=>s.included).length} included sections · ${pending} still to review</strong><br>${pending?'This will be exported as a draft with review states preserved.':'Every included section has been marked reviewed.'}</p><label><input id="include-source" type="checkbox"> Also include the original PDF</label><p>Extraction evidence contains source text, including excluded material. This is an internal review package, not a sanitized public copy.</p><div class="actions"><button class="secondary" data-close>Cancel</button><button class="primary" id="download-package">${pending?'Export draft':'Export package'} ↓</button></div><p id="export-path" hidden></p>`);$('#download-package').onclick=async()=>{const b=$('#download-package');busy(b,true);try{await save();const result=await api(base()+'/export',{revision:project.revision,includeSource:$('#include-source').checked});const link=document.createElement('a');link.href=result.url;link.download='';document.body.append(link);link.click();link.remove();$('#export-path').hidden=false;$('#export-path').textContent='Saved locally: '+result.path;toast('Markdown package exported. A local copy is saved in this conversion’s exports folder.');}catch(e){toast(e.message,true);}finally{busy(b,false);}};};
window.addEventListener('beforeunload',e=>{if(dirty||inFlight){e.preventDefault();e.returnValue='';}});
window.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='s'){e.preventDefault();save().catch(()=>{});}if(e.key==='Escape')cancelCrop();});
(async()=>{try{session=await api('/api/session');await route();}catch(e){toast('Unable to connect to the local app. '+e.message,true);}})();
